{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-08-04T17:10:40Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      fix(chart): fix typo in template
    sha: 282154ff63d792884eeccb84bc95b379f7c66131
  gitHttpUrl: https://github.com/jenkins-x/lighthouse-telemetry-plugin
  gitOwner: jenkins-x
  gitRepository: lighthouse-telemetry-plugin
  name: '{{ .Chart.Name }}'
  version: 0.1.1
status: {}
 
{{- end }}
