{{- if and (.Capabilities.APIVersions.Has "jenkins.io/v1/Release") (hasKey .Values.jx "releaseCRD") (.Values.jx.releaseCRD)}}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-08-04T14:57:12Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: v.behar@free.fr
      name: Vincent Behar
    branch: master
    committer:
      email: v.behar@free.fr
      name: Vincent Behar
    message: |
      feat: add gitops tracing

      see readme for details...
    sha: 399f76d030d59ebde12ab36be56bf041737834e1
  gitHttpUrl: https://github.com/jenkins-x/lighthouse-telemetry-plugin
  gitOwner: jenkins-x
  gitRepository: lighthouse-telemetry-plugin
  name: '{{ .Chart.Name }}'
  version: 0.1.0
status: {}
 
{{- end }}
